#    ______           _   _        _______            _
#   |  ____|         | | (_)      |__   __|          | |
#   | |__  __  _____ | |_ _  ___     | |_ __ __ _  __| | ___  ___
#   |  __| \ \/ / _ \| __| |/ __|    | | '__/ _` |/ _` |/ _ \/ __|
#   | |____ >  < (_) | |_| | (__     | | | | (_| | (_| |  __/\__ \
#   |______/_/\_\___/ \__|_|\___|    |_|_|  \__,_|\__,_|\___||___/



########################
##       Items        ##
########################

#Register items and their properties

Itemlist :
  item1 :
    - name : "item1"
    - id : 1
    - customModelData :

