#    ______           _   _        _______            _
#   |  ____|         | | (_)      |__   __|          | |
#   | |__  __  _____ | |_ _  ___     | |_ __ __ _  __| | ___  ___
#   |  __| \ \/ / _ \| __| |/ __|    | | '__/ _` |/ _` |/ _ \/ __|
#   | |____ >  < (_) | |_| | (__     | | | | (_| | (_| |  __/\__ \
#   |______/_/\_\___/ \__|_|\___|    |_|_|  \__,_|\__,_|\___||___/


########################
##       MARKET       ##
########################

#Set the number of hours sold items are kept in memory for every market item. Integer only.
defaultMovingAverage: 4
#Set the default minimum price for the market.
defaultMinPrice: 0.0
#Set the default maximum price for the market.
defaultMaxPrice: 1000.0
#Set the default market price for the market.
defaultBasePrice: 100.0
#Set the default market volatility for the market.
#A higher volatility means that the market price will fluctuate more.
defaultMarketVolatility: 1.0
#A higher volatility means that the market price will fluctuate more.
defaultDemandMultiplier: 1.0


########################
##  RARES RESSOURCES  ##
########################

#enable : enable the rare ressource.
#name : the name of the rare ressource.
#customModelData [default none]: the custom model data of the rare ressource. If set to none, only items with NO custom model data will be used.

#movingAverage [default "defaultMovingAverage"]: the number of hours sold items are kept in memory for the rare ressource market.
#minPrice [default "defaultMinPrice"]: the minimum price of the rare ressource.
#maxPrice [default "defaultMaxPrice"]: the maximum price of the rare ressource.
#basePrice : the base price of the rare ressource at day 1.
#volatility : the volatility of the rare ressource. A higher volatility means that the market price will fluctuate more.
#demandMultiplier [default "defaultDemandMultiplier"]: the demand multiplier of the rare ressource.

#blocks : the blocks that can drop the rare ressource when broken.
#baseChance [default 0]: the base chance of the rare ressource to drop when breaking the block.
#FortuneModifier [default 0] : the fortune modifier of the rare ressource. Each level of fortune will multiply the base chance by this value.
#allowSilkTouch [default true] : if true, the rare ressource can be obtained with a silk touch pickaxe.

#Rare ressources are new items that will be added to the base loot of a block, entity or fishing. They will have a custom name and a custom model data can be applied.
rareRessources:
  rareStone :
    id : 1
    enabled: true
    name : "Rare Stone"
    material: "EMERALD"
    customModelData: 1
    volatility: 0.5
    dropChance:
      blocks:
        GOLD_ORE:
          baseChance: 17
          FortuneModifier: 1
          allowSilkTouch: false
        DEEPSLATE_GOLD_ORE:
          baseChance: 17
          FortuneModifier: 1
          allowSilkTouch: false
        DIAMOND_ORE:
          baseChance: 22
          FortuneModifier: 1
          allowSilkTouch: false
        EMERALD_ORE:
          baseChance: 50
          FortuneModifier: 10
          allowSilkTouch: false
        DEEPSLATE_EMERALD_ORE:
          baseChance: 50
          FortuneModifier: 10
          allowSilkTouch: false
        REDSTONE_ORE:
          baseChance: 10
          FortuneModifier: 1
          allowSilkTouch: false
        DEEPSLATE_REDSTONE_ORE:
          baseChance: 10
          FortuneModifier: 1
          allowSilkTouch: false
        LAPIS_ORE:
          baseChance: 15
          FortuneModifier: 1
          allowSilkTouch: false
        DEEPSLATE_LAPIS_ORE:
          baseChance: 15
          FortuneModifier: 1
          allowSilkTouch: false
  rareWood:
    id : 2
    enabled: true
    name : "Rare Wood"
    material: "STICK"
    customModelData: 2
    volatility: 1
    dropChance:
      blocks:
        ACACIA_LOG:
          baseChance: 5
          FortuneModifier: 1
        BIRCH_LOG:
          baseChance: 5
          FortuneModifier: 1
        DARK_OAK_LOG:
          baseChance: 5
          FortuneModifier: 1
        JUNGLE_LOG:
          baseChance: 2
          FortuneModifier: 1
        OAK_LOG:
          baseChance: 3
          FortuneModifier: 1
        SPRUCE_LOG:
          baseChance: 2
          FortuneModifier: 1
  rareCrops:
    id : 3
    enabled: true
    name : "Rare Crops"
    material: "WHEAT"
    customModelData: 3
    volatility: 2.5
    dropChance:
      blocks:
        WHEAT:
          baseChance: 3
          FortuneModifier: 1
        CARROTS:
          baseChance: 2
          FortuneModifier: 1
        POTATOES:
          baseChance: 2
          FortuneModifier: 1
        BEETROOTS:
          baseChance: 2
          FortuneModifier: 1
        PUMPKIN:
          baseChance: 5
          FortuneModifier: 1
        MELON:
          baseChance: 5
          FortuneModifier: 1
  rareSoul:
    id : 4
    enabled: true
    name : "Rare Soul"
    material: "FLINT"
    customModelData: 4
    volatility: 1
    dropChance:
      entities:
        ZOMBIE:
          baseChance: 5
        CREEPER:
          baseChance: 15
        SKELETON:
          baseChance: 5
        SPIDER:
          baseChance: 5
        ENDERMAN:
          baseChance: 25
        WITCH:
          baseChance: 10
        PIGLIN:
          baseChance: 5
        PIGLIN_BRUTE:
          baseChance: 5
        ZOMBIFIED_PIGLIN:
          baseChance: 0
        HUSK:
          baseChance: 15
        STRAY:
          baseChance: 15
        CAVE_SPIDER:
          baseChance: 5
        DROWNED:
          baseChance: 10
        BLAZE:
          baseChance: 10
        GHAST:
          baseChance: 75
  rareFish:
    id : 5
    enabled: true
    name : "Rare Fish"
    material: "COD"
    customModelData: 5
    volatility: 1
    dropChance:
      fishing:
        COD:
          baseChance: 4
        SALMON:
          baseChance: 4
        PUFFERFISH:
          baseChance: 8
        TROPICAL_FISH:
          baseChance: 12

#It is also possible to add vanilla ressources to the rare ressources list from the GUI.




villagerHeads :
  PLAINS:
    NONE : "https://textures.minecraft.net/texture/d14bff1a38c9154e5ec84ce5cf00c58768e068eb42b2d89a6bbd29787590106b"
    SHEPHERD: "https://textures.minecraft.net/texture/19e04a752596f939f581930414561b175454d45a0506501e7d2488295a5d5de"
    NITWIT: "https://textures.minecraft.net/texture/d14bff1a38c9154e5ec84ce5cf00c58768e068eb42b2d89a6bbd29787590106b"
    MASON : "https://textures.minecraft.net/texture/2c02c3ffd5705ab488b305d57ff0168e26de70fd3f739e839661ab947dff37b1"
    LIBRARIAN : "https://textures.minecraft.net/texture/e66a53fc707ce1ff88a576ef40200ce8d49fae4acad1e3b3789c7d1cc1cc541a"
    LEATHERWORKER : "https://textures.minecraft.net/texture/f76cf8b7378e889395d538e6354a17a3de6b294bb6bf8db9c701951c68d3c0e6"
    FLETCHER : "https://textures.minecraft.net/texture/17532e90c573a394c7802aa4158305802b59e67f2a2b7e3fd0363aa6ea42b841"
    FISHERMAN : "https://textures.minecraft.net/texture/ac15e5fb56fa16b0747b1bcb05335f55d1fa31561c082b5e3643db5565410852"
    FARMER : "https://textures.minecraft.net/texture/55a0b07e36eafdecf059c8cb134a7bf0a167f900966f1099252d903276461cce"
    CLERIC : "https://textures.minecraft.net/texture/a8856eaafad96d76fa3b5edd0e3b5f45ee49a3067306ad94df9ab3bd5b2d142d"
    CARTOGRAPHER : "https://textures.minecraft.net/texture/94248dd0680305ad73b214e8c6b00094e27a4ddd8034676921f905130b858bdb"
    BUTCHER : "https://textures.minecraft.net/texture/c6774d2df515eceae9eed291c1b40f94adf71df0ab81c7191402e1a45b3a2087"
    ARMORER : "https://textures.minecraft.net/texture/f522db92f188ebc7713cf35b4cbaed1cfe2642a5986c3bde993f5cfb3727664c"
    WEAPONSMITH : "https://textures.minecraft.net/texture/5e409b958bc4fe045e95d325e6e97a533137e33fec7042ac027b30bb693a9d42"
    TOOLSMITH : "https://textures.minecraft.net/texture/7dfa07fd1244eb8945f4ededd00426750b77ef5dfbaf03ed775633459ece415a"
  DESERT :
    NONE : "https://textures.minecraft.net/texture/10bf6df37dac6ca6089d2ba04135f223d4d850df9f09c7ec4eaf8c50764cbc50"
    SHEPHERD: "https://textures.minecraft.net/texture/ce36c366aeb30385cff151a8cf90bac5a8979a55bc2a808875e233d0f81b24a9"
    NITWIT: "https://textures.minecraft.net/texture/598a28aa588c44ff4c93446a7c29d83efac1e5fc8e90d1d6c386c4105dca8f77"
    MASON : "https://textures.minecraft.net/texture/4c4d7ea038187770cc2e4817c9209e19b74f5d288ed633281ecccaf5c8ebc767"
    LIBRARIAN : "https://textures.minecraft.net/texture/ebff5901b97efef922555325e910a6d35cc46967ff8a7c2a0e5753af23ddcff2"
    LEATHERWORKER : "https://textures.minecraft.net/texture/ee61ecbb86487ed16fedb275db92c9c5043a830f52d973ba44b28a7742006b43"
    FLETCHER : "https://textures.minecraft.net/texture/fd4d13baf65ee197dfc6ec28657d25d89f472662204e13cbf761f9412c891335"
    FISHERMAN : "https://textures.minecraft.net/texture/74111111e532d68f0e4f913a4e3aedd0c9dfb2847a8aaf1ffa52b3dabcff86ed"
    FARMER : "https://textures.minecraft.net/texture/355d61a2409eb0b49b3e88b2888467f20a3b06212a10e7b6efb9ce3bc1a0e20f"
    CLERIC: "https://textures.minecraft.net/texture/d24ba760a61dd256c52b325129f46016ae892232a0dea1715f997f7c4d622bef"
    CARTOGRAPHER : "https://textures.minecraft.net/texture/a6f25ea1c39a3d73579e5330e04c2b173ba2fd5c0ca3452be5ff1aae083f6328"
    BUTCHER : "https://textures.minecraft.net/texture/4a6b7136db906a2af54fd446094f5d4d074c4625665bce5706ad6208b8b383f9"
    ARMORER : "https://textures.minecraft.net/texture/d0a3e6c961fb4d6efcf4576455fcd27bc78401256fdf39b25488f31984af96ba"
    WEAPONSMITH : "https://textures.minecraft.net/texture/ebba69f6ee3e128bc2feec78c247b2a2f00c3aea11d8906c728de92c60a542ed"
    TOOLSMITH : "https://textures.minecraft.net/texture/29d904fdae68fb120e9ae0f3537460f2a7c1de9159ab3f2b44c844048febabeb"
  SAVANNA:
    NONE: "https://textures.minecraft.net/texture/dd9ee5d8b58fddd27bc679c0548f55baa845f9f1df5e88c7c5bda6eb9df2b399"
    SHEPHERD: "https://textures.minecraft.net/texture/431c0f4603b51eb6d8892f8ec0b520979041d671b8d378c8b26d097b8f7e1327"
    NITWIT: "https://textures.minecraft.net/texture/dd9ee5d8b58fddd27bc679c0548f55baa845f9f1df5e88c7c5bda6eb9df2b399"
    MASON: "https://textures.minecraft.net/texture/d00364c98af059ae6d581fca6038bee14b869998fb3aa382b3c4775d54e8481f"
    LIBRARIAN: "https://textures.minecraft.net/texture/71f714133ce78d1181c4d5d3e53711ece10c4c9a28201188ee1a6f35cc0fa3ca"
    LEATHERWORKER: "https://textures.minecraft.net/texture/f45c99c80d0345c4be3fc3a2f0d05a3e23a5c4bf7e991568eee64a6806f048c0"
    FLETCHER: "https://textures.minecraft.net/texture/fac222efc6ab4bd1c70351de007e37bf3d028c1d93f08efeaea8a07ecb62867b"
    FISHERMAN: "https://textures.minecraft.net/texture/6acacef5f04bed42e8a808ccec39889e666fb1299e99a9e09060f8cf29e6baf6"
    FARMER: "https://textures.minecraft.net/texture/c9c94faa7ac9b0752dc7da7386b4d8fc34e2916da5b01789275bbcb7dfce7fcb"
    CLERIC: "https://textures.minecraft.net/texture/46cc8fa8379665fbb8c924e45235da1c988c1c523af1b2479796d4a49af1c5c8"
    CARTOGRAPHER: "https://textures.minecraft.net/texture/f2f944222ff693fe088bd543c8efdd3246eab6a34978acde774f7e295dee9e16"
    BUTCHER: "https://textures.minecraft.net/texture/366715115de766c949e8700b7650c8994fd3eeb97bd1836c2e16b5d8d5551b5d"
    ARMORER: "http://textures.minecraft.net/texture/8b6cd9a9fb4b13f49d25b82a14040c045ff57aa8c279cce20a2503b8184d9b9c"
    WEAPONSMITH: "https://textures.minecraft.net/texture/c1beaa099c823332e7780a32110f5b0bfc2546e53fde8e206817325894018f3"
    TOOLSMITH: "https ://textures.minecraft.net/texture/7d586f55be429db689c070c47aa9b1284cd51da493768559d7132df8c8916aed"
  SNOW:
    NONE: "https://textures.minecraft.net/texture/20c641e3d3764ed1c1f1907c4334e2b1303e2152b13d1eb0c605763f97fb258a"
    SHEPHERD: "https://textures.minecraft.net/texture/d1644a552dd06f797413c002d41da52904a7bcfd744c5d2c1fe348d9f66cbbeb"
    NITWIT: "https://textures.minecraft.net/texture/3cc02372f6292a131aa035cef8e52475efa966352e05c2dba374f1309e569dbb"
    MASON: "https://textures.minecraft.net/texture/f6a5a4b492cf3861d3044a911e1364dadf7a2be41fb2f9a5c619de5cc9a5af00"
    LIBRARIAN: "https://textures.minecraft.net/texture/1806f9767f087e3e4c09ad012bfd063d013ba4c3169fbb0efd7538e28d7d83d"
    LEATHERWORKER: "https://textures.minecraft.net/texture/b0e4aa6f5455e321059e202abc9d9e23675663070e92a079e8cb544f7be4c755"
    FLETCHER: "https://textures.minecraft.net/texture/1e126158220e946517b2c20e13805928df06e19c1101bdea2bc5a4fc95f9c011"
    FISHERMAN: "https://textures.minecraft.net/texture/61d644761f706d31c99a593c8d5f7cbbd4372d73fbee8464f482fa6c139d97d4"
    FARMER: "https://textures.minecraft.net/texture/fd95ad3f37bb323785f8d6816763e5a739e2814d611a7ab4afff976f91729faf"
    CLERIC: "https://textures.minecraft.net/texture/7e3d3635ce411abf1e4f373d161d07b8c47e359b6c56f74b413cb494ac746e2d"
    CARTOGRAPHER: "https://textures.minecraft.net/texture/4143895b04cce7b3ad956620bb48d1aaaa6bbdcc10bb3a8c4aa0a55939f050be"
    BUTCHER: "https://textures.minecraft.net/texture/7bb5bfa9ac5412e7d116f9d424e0fd3fa40eedc2c3e7c906c055bb5f4c5c587a"
    ARMORER: "https://textures.minecraft.net/texture/edcb21090cd7e97066a1f1dcae778cda032df8af953767d2a04f4a78dcfc2496"
    WEAPONSMITH: "https://textures.minecraft.net/texture/2844e3ffcc17d4ab0d0eebb6bfdb9603e2f7a095d700028c9db275ae1a95e7f2"
    TOOLSMITH: "https://textures.minecraft.net/texture/fe7db3a5cb5dd6811fa87e2d113aa6057c669078dd62ff28b377f168277d95ce"


