#    ______           _   _        _______            _
#   |  ____|         | | (_)      |__   __|          | |
#   | |__  __  _____ | |_ _  ___     | |_ __ __ _  __| | ___  ___
#   |  __| \ \/ / _ \| __| |/ __|    | | '__/ _` |/ _` |/ _ \/ __|
#   | |____ >  < (_) | |_| | (__     | | | | (_| | (_| |  __/\__ \
#   |______/_/\_\___/ \__|_|\___|    |_|_|  \__,_|\__,_|\___||___/


########################
##  RARES RESSOURCES  ##
########################

#enable : enable the rare ressource.
#name : the name of the rare ressource.
#customModelData [default none]: the custom model data of the rare ressource. If set to none, only items with NO custom model data will be used.
#basePrice : the base price of the rare ressource at day 1.
#volatility : the volatility of the rare ressource. This is used as a multiplier of the base market price update.
#blocks : the blocks that can drop the rare ressource when broken.
#baseChance [default 0]: the base chance of the rare ressource to drop when breaking the block.
#FortuneModifier [default 0] : the fortune modifier of the rare ressource. Each level of fortune will multiply the base chance by this value.
#allowSilkTouch [default true] : if true, the rare ressource can be obtained with a silk touch pickaxe.

#Rare ressources are new items that will be added to the base loot of a block, entity or fishing. They will have a custom name and a custom model data can be applied.
rareRessources:
  rareStone :
    id : 1
    enabled: true
    name : "Rare Stone"
    material: "EMERALD"
    customModelData: 1
    basePrice: 5
    volatility: 0.5
    dropChance:
      blocks:
        GOLD_ORE:
          baseChance: 17
          FortuneModifier: 1
          allowSilkTouch: false
        DEEPSLATE_GOLD_ORE:
          baseChance: 17
          FortuneModifier: 1
          allowSilkTouch: false
        DIAMOND_ORE:
          baseChance: 22
          FortuneModifier: 1
          allowSilkTouch: false
        EMERALD_ORE:
          baseChance: 50
          FortuneModifier: 10
          allowSilkTouch: false
        DEEPSLATE_EMERALD_ORE:
          baseChance: 50
          FortuneModifier: 10
          allowSilkTouch: false
        REDSTONE_ORE:
          baseChance: 10
          FortuneModifier: 1
          allowSilkTouch: false
        DEEPSLATE_REDSTONE_ORE:
          baseChance: 10
          FortuneModifier: 1
          allowSilkTouch: false
        LAPIS_ORE:
          baseChance: 15
          FortuneModifier: 1
          allowSilkTouch: false
        DEEPSLATE_LAPIS_ORE:
          baseChance: 15
          FortuneModifier: 1
          allowSilkTouch: false
  rareWood:
    id : 2
    enabled: true
    name : "Rare Wood"
    material: "STICK"
    customModelData: 2
    basePrice: 3
    volatility: 1
    dropChance:
      blocks:
        ACACIA_LOG:
          baseChance: 5
          FortuneModifier: 1
        BIRCH_LOG:
          baseChance: 5
          FortuneModifier: 1
        DARK_OAK_LOG:
          baseChance: 5
          FortuneModifier: 1
        JUNGLE_LOG:
          baseChance: 2
          FortuneModifier: 1
        OAK_LOG:
          baseChance: 3
          FortuneModifier: 1
        SPRUCE_LOG:
          baseChance: 2
          FortuneModifier: 1
  rareCrops:
    id : 3
    enabled: true
    name : "Rare Crops"
    material: "WHEAT"
    customModelData: 3
    basePrice: 2
    volatility: 2.5
    dropChance:
      blocks:
        WHEAT:
          baseChance: 3
          FortuneModifier: 1
        CARROTS:
          baseChance: 2
          FortuneModifier: 1
        POTATOES:
          baseChance: 2
          FortuneModifier: 1
        BEETROOTS:
          baseChance: 2
          FortuneModifier: 1
        PUMPKIN:
          baseChance: 5
          FortuneModifier: 1
        MELON:
          baseChance: 5
          FortuneModifier: 1
  rareSoul:
    id : 4
    enabled: true
    name : "Rare Soul"
    material: "FLINT"
    customModelData: 4
    basePrice: 10
    volatility: 1
    dropChance:
      entities:
        ZOMBIE:
          baseChance: 5
        CREEPER:
          baseChance: 15
        SKELETON:
          baseChance: 5
        SPIDER:
          baseChance: 5
        ENDERMAN:
          baseChance: 25
        WITCH:
          baseChance: 10
        PIGLIN:
          baseChance: 5
        PIGLIN_BRUTE:
          baseChance: 5
        ZOMBIFIED_PIGLIN:
          baseChance: 0
        HUSK:
          baseChance: 15
        STRAY:
          baseChance: 15
        CAVE_SPIDER:
          baseChance: 5
        DROWNED:
          baseChance: 10
        BLAZE:
          baseChance: 10
        GHAST:
          baseChance: 75
  rareFish:
    id : 5
    enabled: true
    name : "Rare Fish"
    material: "RAW_COD"
    customModelData: 5
    basePrice: 20
    volatility: 1
    dropChance:
      fishing:
        COD:
          baseChance: 4
        SALMON:
          baseChance: 4
        PUFFERFISH:
          baseChance: 8
        TROPICAL_FISH:
          baseChance: 12

#It is also possible to add vanilla ressources to the rare ressources list from the GUI.




villagerHeads :
  PLAINS:
    NONE : "https://textures.minecraft.net/texture/d14bff1a38c9154e5ec84ce5cf00c58768e068eb42b2d89a6bbd29787590106b"
    SHEPHERD: "https://textures.minecraft.net/texture/19e04a752596f939f581930414561b175454d45a0506501e7d2488295a5d5de"
    NITWIT: "https://textures.minecraft.net/texture/d14bff1a38c9154e5ec84ce5cf00c58768e068eb42b2d89a6bbd29787590106b"
    MASON : "https://textures.minecraft.net/texture/2c02c3ffd5705ab488b305d57ff0168e26de70fd3f739e839661ab947dff37b1"
    LIBRARIAN : "https://textures.minecraft.net/texture/e66a53fc707ce1ff88a576ef40200ce8d49fae4acad1e3b3789c7d1cc1cc541a"
    LEATHERWORKER : "https://textures.minecraft.net/texture/f76cf8b7378e889395d538e6354a17a3de6b294bb6bf8db9c701951c68d3c0e6"
    FLETCHER : "https://textures.minecraft.net/texture/17532e90c573a394c7802aa4158305802b59e67f2a2b7e3fd0363aa6ea42b841"
    FISHERMAN : "https://textures.minecraft.net/texture/ac15e5fb56fa16b0747b1bcb05335f55d1fa31561c082b5e3643db5565410852"
    FARMER : "https://textures.minecraft.net/texture/55a0b07e36eafdecf059c8cb134a7bf0a167f900966f1099252d903276461cce"
    CLERIC : "https://textures.minecraft.net/texture/a8856eaafad96d76fa3b5edd0e3b5f45ee49a3067306ad94df9ab3bd5b2d142d"
    CARTOGRAPHER : "https://textures.minecraft.net/texture/94248dd0680305ad73b214e8c6b00094e27a4ddd8034676921f905130b858bdb"
    BUTCHER : "https://textures.minecraft.net/texture/c6774d2df515eceae9eed291c1b40f94adf71df0ab81c7191402e1a45b3a2087"
    ARMORER : "https://textures.minecraft.net/texture/f522db92f188ebc7713cf35b4cbaed1cfe2642a5986c3bde993f5cfb3727664c"
    WEAPONSMITH : "https://textures.minecraft.net/texture/5e409b958bc4fe045e95d325e6e97a533137e33fec7042ac027b30bb693a9d42"
    TOOLSMITH : "https://textures.minecraft.net/texture/7dfa07fd1244eb8945f4ededd00426750b77ef5dfbaf03ed775633459ece415a"
  DESERT :
    NONE : "https://textures.minecraft.net/texture/10bf6df37dac6ca6089d2ba04135f223d4d850df9f09c7ec4eaf8c50764cbc50"
    SHEPHERD: "https://textures.minecraft.net/texture/ce36c366aeb30385cff151a8cf90bac5a8979a55bc2a808875e233d0f81b24a9"
    NITWIT: "https://textures.minecraft.net/texture/598a28aa588c44ff4c93446a7c29d83efac1e5fc8e90d1d6c386c4105dca8f77"
    MASON : "https://textures.minecraft.net/texture/4c4d7ea038187770cc2e4817c9209e19b74f5d288ed633281ecccaf5c8ebc767"
    LIBRARIAN : "https://textures.minecraft.net/texture/ebff5901b97efef922555325e910a6d35cc46967ff8a7c2a0e5753af23ddcff2"
    LEATHERWORKER : "https://textures.minecraft.net/texture/ee61ecbb86487ed16fedb275db92c9c5043a830f52d973ba44b28a7742006b43"
    FLETCHER : "https://textures.minecraft.net/texture/fd4d13baf65ee197dfc6ec28657d25d89f472662204e13cbf761f9412c891335"
    FISHERMAN : "https://textures.minecraft.net/texture/74111111e532d68f0e4f913a4e3aedd0c9dfb2847a8aaf1ffa52b3dabcff86ed"
    FARMER : "https://textures.minecraft.net/texture/355d61a2409eb0b49b3e88b2888467f20a3b06212a10e7b6efb9ce3bc1a0e20f"
    CLERIC: "https://textures.minecraft.net/texture/d24ba760a61dd256c52b325129f46016ae892232a0dea1715f997f7c4d622bef"
    CARTOGRAPHER : "https://textures.minecraft.net/texture/a6f25ea1c39a3d73579e5330e04c2b173ba2fd5c0ca3452be5ff1aae083f6328"
    BUTCHER : "https://textures.minecraft.net/texture/4a6b7136db906a2af54fd446094f5d4d074c4625665bce5706ad6208b8b383f9"
    ARMORER : "https://textures.minecraft.net/texture/d0a3e6c961fb4d6efcf4576455fcd27bc78401256fdf39b25488f31984af96ba"
    WEAPONSMITH : "https://textures.minecraft.net/texture/ebba69f6ee3e128bc2feec78c247b2a2f00c3aea11d8906c728de92c60a542ed"
    TOOLSMITH : "https://textures.minecraft.net/texture/29d904fdae68fb120e9ae0f3537460f2a7c1de9159ab3f2b44c844048febabeb"
