name: ExoticTrades
version: '${version}'
main: org.leralix.exotictrades.ExoticTrades
api-version: '1.19'
load: STARTUP
commands:
  extrade:
    description: admin command of exotictrades
    permission: tan.exotic_trade.admin.command.*
    usage: /<command>
